[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld"

[build]
# Optional: Set your default target platform
# target = "x86_64-pc-windows-gnu"
